class BaseRenderer:
    async def handle_event(self, event_type, payload):
        handler = getattr(self, f"handle_{event_type}", self.handle_unknown)
        await handler(payload)

    async def handle_status(self, payload): ...
    async def handle_iteration(self, payload): ...
    async def handle_tool_call(self, payload): ...
    async def handle_tool_result(self, payload): ...
    async def handle_token(self, payload): ...
    async def handle_done(self, payload): ...
    async def handle_unknown(self, payload): ...
