.PHONY: python-dev python-deploy python-delete

python-dev:
	$(MAKE) -C python-cloudflare dev

python-deploy:
	$(MAKE) -C python-cloudflare deploy

python-delete:
	$(MAKE) -C python-cloudflare delete
