[project]
name = "saving-money-with-batch-and-flex"
version = "0.1.0"
description = "Workshop code for reducing eval costs with OpenAI Batch and Flex"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "minsearch>=0.0.10",
    "openai>=2.31.0",
    "pandas>=3.0.2",
    "python-dotenv>=1.2.2",
    "requests>=2.33.1",
    "tqdm>=4.67.3",
]

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
]
